import React, { useState } from 'react';
import {
  Users,
  ArrowRight,
  ShieldCheck,
  CheckCircle2,
  Download,
  Activity,
  Sliders,
  ChevronDown,
  Globe2,
  DollarSign,
  TrendingUp,
  Award,
  Layers,
  Sparkles,
  PieChart
} from 'lucide-react';
import { CTASection } from '../../components/CTA/CTASection';

interface PartnerAreaPageProps {
  onOpenAccount: () => void;
}

export const PartnerAreaPage: React.FC<PartnerAreaPageProps> = ({ onOpenAccount }) => {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [activePartnerTier, setActivePartnerTier] = useState<'master' | 'sub_ib' | 'affiliate'>('master');

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const features = [
    {
      icon: Users,
      title: 'Unlimited Multi-Tier Sub-IB Trees',
      description: 'Configure up to 10 tiers of master IBs, regional partners, and sub-affiliates with custom revenue share and pip rebate splits.',
      badge: 'Multi-Tier IB'
    },
    {
      icon: DollarSign,
      title: 'Real-Time Commission Calculation Engine',
      description: 'Instant rebate calculation on closed trades. IB earnings automatically credited to partner wallets in real-time or daily batches.',
      badge: 'Rebate Engine'
    },
    {
      icon: PieChart,
      title: 'Advanced Marketing & Link Tracking',
      description: 'Generate dynamic referral tracking links, custom QR codes, promotional banners, and campaign conversion analytics.',
      badge: 'Analytics'
    },
    {
      icon: TrendingUp,
      title: 'Flexible Rebate Models',
      description: 'Support USD per lot, spread markup percentage, net deposit CPA commissions, and volume bonus tier incentives.',
      badge: 'Flexible Models'
    },
    {
      icon: Award,
      title: 'Partner Rewards & Performance Tiers',
      description: 'Automated partner rank advancement (Bronze, Silver, Gold, Platinum VIP) with custom perks and higher rebate payouts.',
      badge: 'Gamification'
    },
    {
      icon: ShieldCheck,
      title: 'Automated Partner Payout Vault',
      description: 'Self-service partner withdrawals with automated compliance verification, crypto payouts, and Bank Wire processing.',
      badge: 'Vault'
    }
  ];

  const specs = [
    { module: 'Rebate Calculation Latency', tier: 'Real-Time Trade Stream Sync', status: 'Instant' },
    { module: 'Multi-Tier Tree Depth', tier: 'Up to 10 Sub-IB Hierarchy Tiers', status: 'Unlimited' },
    { module: 'Supported Rebate Assets', tier: 'FX, Crypto, Indices, Commodities', status: 'All Instruments' },
    { module: 'Tracking Attribution Window', tier: 'Cookie-Based 90-Day / Lifetime Sticky', status: 'Configurable' },
    { module: 'Partner Portal Languages', tier: '24 Native Languages', status: 'Global' },
  ];

  const faqs = [
    {
      q: 'How does the multi-tier IB commission structure work?',
      a: 'Master IBs receive a percentage of the trading volume generated by their sub-IBs and referred traders. You can customize rebate splits down to 10 sub-tiers.'
    },
    {
      q: 'Are IB rebates calculated in real-time?',
      a: 'Yes. As soon as a trade is closed on MT4, MT5, or cTrader, the commission is calculated by the Back Office and instantly reflected in the IB Partner wallet.'
    },
    {
      q: 'Can IBs create custom tracking links and campaigns?',
      a: 'Yes. Partners can generate custom tracking URLs, assign sub-campaign tags, track click-through conversions, and download marketing materials directly from their portal.'
    },
    {
      q: 'What payout methods are available for IBs?',
      a: 'Partners can withdraw their earned commissions via Bank Wire, Crypto (USDT), Skrill, Neteller, or transfer directly into their trading accounts.'
    }
  ];

  return (
    <div className="min-h-screen bg-white dark:bg-[#090D14] text-slate-900 dark:text-white font-sans transition-colors duration-300">
      
      {/* SECTION 1: HERO & INTERACTIVE PARTNER MOCKUP */}
      <section className="relative overflow-hidden pt-16 pb-24 lg:pt-24 lg:pb-32 border-b border-slate-200 dark:border-slate-800/80">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] bg-emerald-500/10 dark:bg-emerald-500/15 rounded-full blur-[140px] pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-[500px] h-[300px] bg-teal-500/5 dark:bg-teal-500/10 rounded-full blur-[100px] pointer-events-none" />

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center space-y-6 max-w-4xl mx-auto">
            
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-mono font-bold uppercase tracking-wider bg-emerald-50 dark:bg-emerald-950/70 text-emerald-800 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800/60 shadow-xs">
              <Users className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
              <span>Introducing Broker & Affiliate Module</span>
            </div>

            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.15] text-slate-900 dark:text-white">
              Institutional IB Partner{' '}
              <span className="bg-gradient-to-r from-emerald-600 via-teal-500 to-emerald-500 dark:from-emerald-400 dark:via-teal-400 dark:to-emerald-400 bg-clip-text text-transparent">
                & Affiliate Management Portal
              </span>
            </h1>

            <p className="text-lg sm:text-xl text-slate-600 dark:text-slate-300 max-w-3xl mx-auto leading-relaxed font-medium">
              Scale your brokerage acquisition network with automated multi-tier IB tracking, real-time pip rebate calculations, flexible CPA structures, and self-service partner dashboards.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
              <button
                onClick={onOpenAccount}
                className="w-full sm:w-auto px-8 py-4 bg-emerald-600 hover:bg-emerald-500 text-white font-extrabold text-sm rounded-xl shadow-xl shadow-emerald-600/20 transition-all flex items-center justify-center gap-2 cursor-pointer group"
              >
                <span>Explore Partner Portal Demo</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </button>
              <button
                onClick={onOpenAccount}
                className="w-full sm:w-auto px-7 py-4 font-bold text-sm rounded-xl border transition-all flex items-center justify-center gap-2 cursor-pointer bg-slate-50 dark:bg-[#121520] hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-800 dark:text-slate-200 border-slate-200 dark:border-slate-800 shadow-xs"
              >
                <Download className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                <span>IB Rebate Calculation Spec Sheet</span>
              </button>
            </div>

            <div className="pt-6 flex flex-wrap items-center justify-center gap-8 text-xs font-mono text-slate-500 dark:text-slate-400 border-t border-slate-200 dark:border-slate-800/80">
              <span className="flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4 text-emerald-500" /> 10-Tier Multi-Sub-IB Trees</span>
              <span className="flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4 text-emerald-500" /> Real-Time Trade Rebates</span>
              <span className="flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4 text-emerald-500" /> Automated CPA & Revenue Share</span>
            </div>
          </div>

          {/* Interactive Partner Tracker Preview Card */}
          <div className="mt-14 max-w-5xl mx-auto rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-[#121520] shadow-2xl p-6 sm:p-8 space-y-6">
            
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-200 dark:border-slate-800 pb-4">
              <div className="flex items-center gap-3">
                <Users className="w-5 h-5 text-emerald-500" />
                <span className="text-xs font-mono font-bold text-slate-900 dark:text-white">Master IB Dashboard • Tier: VIP Platinum Partner</span>
              </div>
              <div className="flex items-center gap-2">
                {(['master', 'sub_ib', 'affiliate'] as const).map((tier) => (
                  <button
                    key={tier}
                    onClick={() => setActivePartnerTier(tier)}
                    className={`px-3 py-1.5 text-xs font-mono font-bold rounded-lg transition-all cursor-pointer uppercase ${
                      activePartnerTier === tier
                        ? 'bg-emerald-600 text-white shadow-sm'
                        : 'bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-400 hover:text-emerald-500'
                    }`}
                  >
                    {tier}
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              
              <div className="p-5 rounded-xl bg-white dark:bg-[#090D14] border border-slate-200 dark:border-slate-800 space-y-3">
                <div className="flex items-center justify-between text-xs font-mono text-slate-500">
                  <span>Total Monthly Rebates</span>
                  <span className="text-emerald-500 font-bold">+24.5%</span>
                </div>
                <div className="text-2xl font-black font-mono text-slate-900 dark:text-white">$38,490.20</div>
                <div className="text-[11px] text-slate-500 font-mono">1,842 Traded Lots Managed</div>
              </div>

              <div className="p-5 rounded-xl bg-white dark:bg-[#090D14] border border-slate-200 dark:border-slate-800 space-y-3">
                <div className="flex items-center justify-between text-xs font-mono text-slate-500">
                  <span>Referred Active Clients</span>
                  <span className="text-emerald-500 font-bold">Live</span>
                </div>
                <div className="text-2xl font-black font-mono text-slate-900 dark:text-white">412 Accounts</div>
                <div className="text-[11px] text-slate-500 font-mono">Sub-IB Network: 14 Partners</div>
              </div>

              <div className="p-5 rounded-xl bg-white dark:bg-[#090D14] border border-slate-200 dark:border-slate-800 space-y-3">
                <div className="flex items-center justify-between text-xs font-mono text-slate-500">
                  <span>Rebate Tier SLA</span>
                  <span className="text-emerald-500 font-bold">$12.00 / Lot</span>
                </div>
                <div className="text-xl font-bold font-mono text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5">
                  <Award className="w-5 h-5" />
                  <span>Platinum VIP Status</span>
                </div>
                <p className="text-[11px] text-slate-500 font-mono">Instant Payout Available</p>
              </div>

            </div>

          </div>
        </div>
      </section>

      {/* SECTION 2: CORE FEATURES GRID */}
      <section className="py-24 bg-slate-50/50 dark:bg-[#0c1017] border-b border-slate-200 dark:border-slate-800/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16">
          <div className="text-center space-y-4 max-w-3xl mx-auto">
            <h2 className="text-3xl sm:text-4xl font-black tracking-tight text-slate-900 dark:text-white">
              Institutional IB & Affiliate Features
            </h2>
            <p className="text-slate-600 dark:text-slate-300 font-medium">
              Empower your partner managers and master IBs with powerful acquisition tools and real-time commission tracking.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((item, idx) => {
              const Icon = item.icon;
              return (
                <div
                  key={idx}
                  className="p-8 rounded-2xl bg-white dark:bg-[#121520] border border-slate-200 dark:border-slate-800 hover:border-emerald-500/50 transition-all duration-300 shadow-sm hover:shadow-xl group space-y-4"
                >
                  <div className="flex items-center justify-between">
                    <div className="w-12 h-12 rounded-xl bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-200 dark:border-emerald-800/50 flex items-center justify-center text-emerald-600 dark:text-emerald-400 group-hover:scale-110 transition-transform">
                      <Icon className="w-6 h-6" />
                    </div>
                    <span className="text-[10px] font-mono font-bold uppercase tracking-wider bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 px-2.5 py-1 rounded-full">
                      {item.badge}
                    </span>
                  </div>
                  <h3 className="text-xl font-bold text-slate-900 dark:text-white">
                    {item.title}
                  </h3>
                  <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed font-medium">
                    {item.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* SECTION 3: WORKFLOW VISUALIZER */}
      <section className="py-24 border-b border-slate-200 dark:border-slate-800/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16">
          <div className="text-center space-y-4 max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-mono font-bold uppercase bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800/50">
              <Activity className="w-3.5 h-3.5" />
              <span>Partner Acquisition Pipeline</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-black tracking-tight text-slate-900 dark:text-white">
              Automated Partner Commission Pipeline
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            {[
              { step: '01', title: 'Partner Onboarding', desc: 'IB registers and receives personalized tracking links and promotional campaign assets.' },
              { step: '02', title: 'Trader Registration', desc: 'Referred traders register and open live MT4/MT5 trading accounts under the IB referral tree.' },
              { step: '03', title: 'Real-Time Rebates', desc: 'As traders execute positions, pip rebates and commissions calculate in real-time.' },
              { step: '04', title: 'Automated Payouts', desc: 'Commissions credited directly to IB Wallet for instant withdrawal via Wire or Crypto.' },
            ].map((step, i) => (
              <div key={i} className="p-6 rounded-2xl bg-slate-50 dark:bg-[#121520] border border-slate-200 dark:border-slate-800 space-y-3">
                <span className="text-3xl font-mono font-black text-emerald-500/40 dark:text-emerald-400/30">{step.step}</span>
                <h4 className="text-lg font-bold text-slate-900 dark:text-white">{step.title}</h4>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 4: TECHNICAL SPECS TABLE */}
      <section className="py-24 bg-slate-50/50 dark:bg-[#0c1017] border-b border-slate-200 dark:border-slate-800/80">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
          <div className="text-center space-y-4">
            <h2 className="text-3xl font-black tracking-tight text-slate-900 dark:text-white">
              Partner Engine Benchmarks & Specifications
            </h2>
          </div>

          <div className="rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden bg-white dark:bg-[#121520]">
            <table className="w-full text-left text-xs font-mono">
              <thead className="bg-slate-100 dark:bg-slate-900 text-slate-700 dark:text-slate-300 border-b border-slate-200 dark:border-slate-800 uppercase font-bold">
                <tr>
                  <th className="py-4 px-6">System Component</th>
                  <th className="py-4 px-6">Specification Tier</th>
                  <th className="py-4 px-6 text-right">Status SLA</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 dark:divide-slate-800/60 font-medium text-slate-800 dark:text-slate-200">
                {specs.map((item, idx) => (
                  <tr key={idx} className="hover:bg-slate-50 dark:hover:bg-slate-800/40">
                    <td className="py-4 px-6 font-bold">{item.module}</td>
                    <td className="py-4 px-6 text-slate-600 dark:text-slate-400">{item.tier}</td>
                    <td className="py-4 px-6 text-right text-emerald-600 dark:text-emerald-400 font-bold">{item.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* SECTION 5: INTEGRATION ECOSYSTEM */}
      <section className="py-24 border-b border-slate-200 dark:border-slate-800/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12 text-center">
          <h2 className="text-3xl font-black text-slate-900 dark:text-white">
            Supported Partner Rebate Instruments
          </h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-4">
            {['Forex Majors & Minors', 'Crypto Pairs', 'Stock Indices', 'Precious Metals', 'Energies & Commodities', 'US & EU Stocks'].map((item, i) => (
              <div key={i} className="p-4 rounded-xl bg-slate-50 dark:bg-[#121520] border border-slate-200 dark:border-slate-800 font-mono font-bold text-xs text-slate-700 dark:text-slate-300 flex items-center justify-center">
                {item}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 6: FAQ ACCORDION */}
      <section className="py-24 bg-slate-50/50 dark:bg-[#0c1017] border-b border-slate-200 dark:border-slate-800/80">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
          <div className="text-center space-y-3">
            <h2 className="text-3xl font-black text-slate-900 dark:text-white">
              IB Partner Area FAQ
            </h2>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div
                key={idx}
                className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#121520] overflow-hidden"
              >
                <button
                  onClick={() => toggleFaq(idx)}
                  className="w-full px-6 py-4 text-left font-bold text-sm text-slate-900 dark:text-white flex items-center justify-between cursor-pointer"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`w-4 h-4 transition-transform ${openFaq === idx ? 'rotate-180 text-emerald-500' : ''}`} />
                </button>
                {openFaq === idx && (
                  <div className="px-6 pb-4 text-xs text-slate-600 dark:text-slate-300 leading-relaxed border-t border-slate-100 dark:border-slate-800/60 pt-3">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 7: CTA */}
      <CTASection onOpenAccount={onOpenAccount} title="Empower Your IB & Affiliate Network Today." />

    </div>
  );
};
